In [1]:
import numpy as np

In [ ]:
np.

In [8]:
arr = np.array([1, 2, 3])
print(arr)
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr)
arr = np.array((1, 3, 2))
print(arr)

[1 2 3]
[[1 2 3]
 [4 5 6]]
[1 3 2]


In [7]:
arr = np.array([
    [-1, 2, 0, 4],
    [4, -0.5, 6, 0],
    [2.6, 0, 7, 8],
    [3, -7, 4, 2.0]
])
arr2 = arr[:2, ::2]
print("First 2 rows and alternate columns:\n", arr2)
arr3 = arr[[1, 1, 0, 3], [3, 2, 1, 0]]
print("Selected elements:", arr3)

First 2 rows and alternate columns:
 [[-1.  0.]
 [ 4.  6.]]
Selected elements: [0. 6. 2. 3.]


In [6]:
a = np.array([[1, 2],
              [3, 4]])
b = np.array([[4, 3],
              [2, 1]])
print("Adding 1 to every element:\n", a + 1)
print("Subtracting 2 from each element:\n", b - 2)
print("Sum of all array elements:", a.sum())
print("Array sum:\n", a + b)

Adding 1 to every element:
 [[2 3]
 [4 5]]
Subtracting 2 from each element:
 [[ 2  1]
 [ 0 -1]]
Sum of all array elements: 10
Array sum:
 [[5 5]
 [5 5]]


In [9]:
x = np.array([1, 2])  
print(x.dtype)         
x = np.array([1.0, 2.0]) 
print(x.dtype)  
x = np.array([1, 2], dtype = np.int64)   
print(x.dtype)

int32
float64
int64


In [10]:
arr1 = np.array([[4, 7], [2, 6]], dtype=np.float64)
arr2 = np.array([[3, 6], [2, 8]], dtype=np.float64)
print(np.add(arr1, arr2))
print(np.sum(arr1))
print(np.sqrt(arr1))
print(arr1.T)

[[ 7. 13.]
 [ 4. 14.]]
19.0
[[2.         2.64575131]
 [1.41421356 2.44948974]]
[[4. 2.]
 [7. 6.]]


In [11]:
arr = np.array([1, 2, 3])
print("Array with Rank 1: \n", arr)
arr = np.array([[1, 2, 3], [4, 5, 6]])
print("Array with Rank 2: \n", arr)

Array with Rank 1: 
 [1 2 3]
Array with Rank 2: 
 [[1 2 3]
 [4 5 6]]


In [12]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[4, 3], [2, 1]])
print("Array sum:\n", a + b)

Array sum:
 [[5 5]
 [5 5]]


In [13]:
a = np.array([1, 2, 3])
b = np.array([4])
print("Broadcasted sum:\n", a + b)

Broadcasted sum:
 [5 6 7]


In [14]:
arr_zero = np.zeros((3, 4))  
print(arr_zero)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [15]:
arr_one = np.ones((2, 3))  
print(arr_one)

[[1. 1. 1.]
 [1. 1. 1.]]
