In [3]:
import numpy as np

arr1 = np.array([10, 20, 30, 40, 50])
print("1D Array:", arr1)

arr2 = np.array([[1, 2, 3],
                 [4, 5, 6]])
print("\n2D Array:\n", arr2)

1D Array: [10 20 30 40 50]

2D Array:
 [[1 2 3]
 [4 5 6]]


In [9]:
print("\nZeros Array:")
print(np.zeros((2, 3)))

print("\nOnes Array:")
print(np.ones((3, 3)))

print("\nIdentity Matrix:")
print(np.eye(4))

print("\nArray with Range:")
print(np.arange(1, 11))

print("\nEven Numbers:")
print(np.arange(2, 21, 2))

print("\nLinearly Spaced Values:")
print(np.linspace(0, 10, 5))

# ===========================
# Array Properties
# ===========================

print("\nShape:", arr2.shape)
print("Size:", arr2.size)
print("Dimensions:", arr2.ndim)
print("Data Type:", arr2.dtype)

# ===========================
# Mathematical Operations
# ===========================

print("\nAddition:", arr1 + 5)
print("Subtraction:", arr1 - 5)
print("Multiplication:", arr1 * 2)
print("Division:", arr1 / 2)
print("Square:", arr1 ** 2)
print("Square Root:", np.sqrt(arr1))

# ===========================
# Statistical Functions
# ===========================

print("\nSum:", np.sum(arr1))
print("Mean:", np.mean(arr1))
print("Median:", np.median(arr1))
print("Maximum:", np.max(arr1))
print("Minimum:", np.min(arr1))
print("Standard Deviation:", np.std(arr1))
print("Variance:", np.var(arr1))



Zeros Array:
[[0. 0. 0.]
 [0. 0. 0.]]

Ones Array:
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

Identity Matrix:
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]

Array with Range:
[ 1  2  3  4  5  6  7  8  9 10]

Even Numbers:
[ 2  4  6  8 10 12 14 16 18 20]

Linearly Spaced Values:
[ 0.   2.5  5.   7.5 10. ]

Shape: (2, 3)
Size: 6
Dimensions: 2
Data Type: int32

Addition: [15 25 35 45 55]
Subtraction: [ 5 15 25 35 45]
Multiplication: [ 20  40  60  80 100]
Division: [ 5. 10. 15. 20. 25.]
Square: [ 100  400  900 1600 2500]
Square Root: [3.16227766 4.47213595 5.47722558 6.32455532 7.07106781]

Sum: 150
Mean: 30.0
Median: 30.0
Maximum: 50
Minimum: 10
Standard Deviation: 14.142135623730951
Variance: 200.0


In [11]:
# ===========================
# Array Indexing & Slicing
# ===========================

print("\nFirst Element:", arr1[0])
print("Last Element:", arr1[-1])
print("Elements from Index 1 to 3:", arr1[1:4])

# ===========================
# Reshaping Arrays
# ===========================

a = np.arange(1, 13)

print("\nOriginal Array:")
print(a)

print("\nReshaped to 3x4:")
print(a.reshape(3, 4))

# ===========================
# Array Concatenation
# ===========================

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print("\nConcatenated Array:")
print(np.concatenate((a, b)))

# ===========================
# Sorting
# ===========================

arr = np.array([8, 3, 9, 1, 5])

print("\nOriginal:", arr)
print("Sorted:", np.sort(arr))

# ===========================
# Random Numbers
# ===========================

print("\nRandom Integers:")
print(np.random.randint(1, 100, 5))

print("\nRandom Decimal Numbers:")
print(np.random.rand(3))

# ===========================
# Matrix Operations
# ===========================

A = np.array([[1, 2],
              [3, 4]])

B = np.array([[5, 6],
              [7, 8]])

print("\nMatrix Addition:")
print(A + B)

print("\nMatrix Subtraction:")
print(A - B)

print("\nMatrix Multiplication:")
print(np.dot(A, B))

print("\nTranspose of Matrix A:")
print(A.T)

# ===========================
# Logical Operations
# ===========================

print("\nElements Greater Than 25:")
print(arr1 > 25)

print("\nValues Greater Than 25:")
print(arr1[arr1 > 25])

# ===========================
# Aggregate Operations
# ===========================

matrix = np.array([[2, 4, 6],
                   [8, 10, 12]])

print("\nRow-wise Sum:")
print(np.sum(matrix, axis=1))

print("\nColumn-wise Sum:")
print(np.sum(matrix, axis=0))


First Element: 10
Last Element: 50
Elements from Index 1 to 3: [20 30 40]

Original Array:
[ 1  2  3  4  5  6  7  8  9 10 11 12]

Reshaped to 3x4:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Concatenated Array:
[1 2 3 4 5 6]

Original: [8 3 9 1 5]
Sorted: [1 3 5 8 9]

Random Integers:
[16 49 61 66 56]

Random Decimal Numbers:
[0.51558473 0.36027839 0.93564595]

Matrix Addition:
[[ 6  8]
 [10 12]]

Matrix Subtraction:
[[-4 -4]
 [-4 -4]]

Matrix Multiplication:
[[19 22]
 [43 50]]

Transpose of Matrix A:
[[1 3]
 [2 4]]

Elements Greater Than 25:
[False False  True  True  True]

Values Greater Than 25:
[30 40 50]

Row-wise Sum:
[12 30]

Column-wise Sum:
[10 14 18]
